#!/bin/bash

npx google-closure-compiler \
--language_in ECMASCRIPT6 \
--language_out ECMASCRIPT6 \
--warning_level DEFAULT \
--compilation_level WHITESPACE_ONLY \
--isolation_mode IIFE \
--js "./../../lib/rune.js" \
--js "./../../src/scope/Manifest.js" \
--js "./../../src/data/manifest/Resources.js" \
--js "./../../src/Entity/Bullet.js" \
--js "./../../src/Entity/Character.js" \
--js "./../../src/Entity/Clouds.js" \
--js "./../../src/Entity/Melons/Melon.js" \
--js "./../../src/Entity/Melons/type/MelonL.js" \
--js "./../../src/Entity/Melons/type/MelonM.js" \
--js "./../../src/Entity/Melons/type/MelonS.js" \
--js "./../../src/wave/Wave.js" \
--js "./../../src/wave/type/Wave01.js" \
--js "./../../src/wave/type/Wave02.js" \
--js "./../../src/wave/type/Wave03.js" \
--js "./../../src/wave/type/Wave04.js" \
--js "./../../src/wave/type/Wave05.js" \
--js "./../../src/wave/type/Wave06.js" \
--js "./../../src/Entity/Powerup/Powerups.js" \
--js "./../../src/Entity/Powerup/type/Shield.js" \
--js "./../../src/Entity/Powerup/type/Coin.js" \
--js "./../../src/scene/Menu.js" \
--js "./../../src/scene/Game.js" \
--js "./../../src/scene/HowTo.js" \
--js "./../../src/scene/Highscore.js" \
--js "./../../src/scene/Gameover.js" \
--js "./../../src/system/Main.js" \
--js "./../../src/scope/Alias.js" \
--js_output_file "./../../dist/game.js";